Fix ``NameError`` in :func:`asyncio.gather` when initial type check fails.
